modLoader="javafml"
loaderVersion="[11,)"
license="MIT"
issueTrackerURL="https://github.com/brainage04/ModernMinecraftModTemplate/issues"

[[mods]]
modId="modernminecraftmodtemplate"
version="${version}"
displayName="ModernMinecraftModTemplate"
authors="brainage04"
description='''My modern Minecraft modding template.'''
iconFile="assets/modernminecraftmodtemplate/icon.png"
displayURL="https://github.com/brainage04/ModernMinecraftModTemplate"

[[mixins]]
config="modernminecraftmodtemplate.mixins.json"

[[mixins]]
config="modernminecraftmodtemplate.client.mixins.json"

[[dependencies.modernminecraftmodtemplate]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.modernminecraftmodtemplate]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.modernminecraftmodtemplate]]
modId="fzzy_config"
type="required"
versionRange="[0.7.6,)"
ordering="AFTER"
side="BOTH"
